version: '3'
services:
  phoenix:
    build:
      context: . 
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: my_scrobbles_bot_prod
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on: 
      - db
    volumes:
            - ./uploads:/app/uploads

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  files:
    image: "busybox"
    volumes:
      - /home/ubuntu/my_scrobbles_bot/uploads
    command: "true"


volumes:
  pgdata:
  uploads:
