version: '3'
services:
  phoenix:
    build:
      context: . 
    ports:
      - "4000:4000"
    volumes:
            - ./uploads:/app/uploads


  adminer:
    image: adminer
    restart: always
    ports:
      - 7856:8080
  
  files:
    image: "busybox"
    volumes:
      - /home/ubuntu/somali_live_project/uploads
    command: "true"


volumes:
  uploads:
