version: '3'
services:
  phoenix:
    build:
      context: . 
    environment:
      PG_USERNAME: postgres
      PGPASSWORD: postgres
      PG_DATABASE: my_scrobbles_bot_prod
      PG_PORT: 5432
      PG_HOST: db
    ports:
      - "4000:4000"
    depends_on: 
      - db
    volumes:
            - ./uploads:/app/uploads

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  files:
    image: "busybox"
    volumes:
      - /home/ubuntu/somali_live_project/uploads
    command: "true"


volumes:
  pgdata:
  uploads:
