version: '3'
services:
  phoenix:
    build:
      context: . 
    environment:
      PG_USERNAME: postgres
      PGPASSWORD: postgres
      PG_DATABASE: my_scrobbles_bot_prod
      PG_PORT: 5432
      PG_HOST: localhost
      LAST_FM_TOKEN: 92948e038ad0708dbbed57e977db5fce
      MUSIC_X_MATCH_TOKEN: f1b5674f072c7c7b775118528762ec0d
      TELEGRAM_BOT_KEY: 1993314727:AAHkFDgqq-NWCOW04DlnD1sZ78iRGgoig9w
    ports:
      - "4000:4000"
    extra_hosts:
      - localhost:${LOCAL_IP}
    volumes:
            - ./uploads:/app/uploads

  files:
    image: "busybox"
    volumes:
      - /home/ubuntu/somali_live_project/uploads
    command: "true"


volumes:
  uploads:

