version: '3'
services:
  phoenix:
    build:
      context: . 
    environment:
      PG_USERNAME: postgres
      PGPASSWORD: N3MmsJzzYNPS2RJU
      PGDATABASE: my_scrobbles_bot_prod
      PG_HOST: localhost
      PG_PORT: 5432
    ports:
      - "4000:4000"
    volumes:
            - ./uploads:/app/uploads


  adminer:
    image: adminer
    restart: always
    ports:
      - 7856:8080
  
  files:
    image: "busybox"
    volumes:
      - /home/ubuntu/somali_live_project/uploads
    command: "true"


volumes:
  pgdata:
  uploads:
