version: '3'

services: 
  bff_api:
    build:
      context: ../
      dockerfile: _docker/Dockerfile.prod
    env_file: ./env/prod.env
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "4002:4000"
    networks:
      - local-cloud

networks:
  local-cloud:
    external: true
    name: local-cloud